### ISSUE TITLE
Distribution gives no instructions for contributors

### ISSUE THREAD

**Issue by karenetheridge** [tobyink/p5-kavorka#11]
I submitted a PR a few weeks ago -- https://github.com/tobyink/p5-kavorka/pull/10

This failed in travis - presumably because the new prereq wasn't added for namespace::autoclean -- however I have no idea how to add this, as you're using a custom build solution with no documentation.

Please could you add a document to your repositories that gave some sort of guidance to contributors?  As an example, this is the template for the CONTRIBUTING file I inject into all my distributions:  https://github.com/karenetheridge/Dist-Zilla-PluginBundle-Author-ETHER/blob/master/share/CONTRIBUTING

**Comment by tobyink** [comment]
The release tarball already includes a `CONTRIBUTING` file. I don't want to clutter up my repository with boilerplate.
