### ISSUE TITLE
Entire test suite fails with multiple errors trying to find object methods

### ISSUE THREAD

**Issue by greeneg** [tobyink/p5-kavorka#22]
The entire test suite fails with several errors trying to locate object methods in Kavorka::Sub::Fun, Kavorka::Sub::Method, and Kavorka::Multi.

Error output follows:
t/01basic.t .................... ok
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/02named-functions.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 48.
t/03anon-functions.t ........... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/04named-methods.t ............ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 48.
t/05anon-methods.t ............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/10positional.t ............... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/11named.t .................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/12invocant.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/13slurpy.t ................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/14underscores.t .............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/20modifiers-moo.t ............ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/21modifiers-moose.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/22modifiers-mouse.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/23modifiers-tiny.t ........... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/24multimodifiers.t ........... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/28modifiers-augment.t ........ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/29modifiers-override.t ....... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Multi" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/30multi.t .................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Multi" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/31multimulti.t ............... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Multi" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/32multiredefine.t ............ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Multi" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/33cacheinvalidationishard.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/50types.t .................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/51coerce.t ................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/52typeexpr.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/53typeexpr-moosextypes.t ..... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182, <DATA> line 1.
t/54typefallback.t ............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/59valueconstraints.t ......... 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/60alias.t .................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/61ro.t ....................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/62locked.t ................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/63freshoverride.t ............ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/69traits.t ................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/70introspection.t ............ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't call method "add_attribute" on an undefined value at /opt/Perl/lib/perl5/site_perl/5.24.0/Moo/HandleMoose.pm line 169.
Compilation failed in require at t/71moosemeta.t line 34.
BEGIN failed--compilation aborted at t/71moosemeta.t line 34.
t/71moosemeta.t ................ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/80returntype.t ............... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/90closures.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/91lvalue.t ................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/92weirdvars.t ................ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Fun" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/93prototypes.t ............... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/94bypassparsing.t ............ 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/95rolesatisfaction.t ......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
t/98undefer.t .................. skipped: Test requires module 'Moops' but it's not found
Can't locate object method "_set_declared_name" via package "Kavorka::Sub::Method" at /Users/greeneg/.cpan/build/Kavorka-0.037-1/blib/lib/Kavorka/Sub.pm line 182.
t/99threads.t .................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 

Test Summary Report
-------------------
t/02named-functions.t        (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/03anon-functions.t         (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/04named-methods.t          (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/05anon-methods.t           (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/10positional.t             (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/11named.t                  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/12invocant.t               (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/13slurpy.t                 (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/14underscores.t            (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/20modifiers-moo.t          (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/21modifiers-moose.t        (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/22modifiers-mouse.t        (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/23modifiers-tiny.t         (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/24multimodifiers.t         (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/28modifiers-augment.t      (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/29modifiers-override.t     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/30multi.t                  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/31multimulti.t             (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/32multiredefine.t          (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/33cacheinvalidationishard.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/50types.t                  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/51coerce.t                 (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/52typeexpr.t               (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/53typeexpr-moosextypes.t   (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/54typefallback.t           (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/59valueconstraints.t       (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
t/60alias.t                  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/61ro.t                     (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/62locked.t                 (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/63freshoverride.t          (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/69traits.t                 (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/70introspection.t          (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/71moosemeta.t              (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/80returntype.t             (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/90closures.t               (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/91lvalue.t                 (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/92weirdvars.t              (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/93prototypes.t             (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/94bypassparsing.t          (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/95rolesatisfaction.t       (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/99threads.t                (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=43, Tests=1,  9 wallclock secs ( 0.09 usr  0.08 sys +  7.06 cusr  0.77 csys =  8.00 CPU)
Result: FAIL
Failed 41/43 test programs. 0/1 subtests failed.
gmake: *** [Makefile:953: test_dynamic] Error 255

Platform: macOS 10.12, perl 5.24.1

**Comment by pwr22** [comment]
I am seeing the same issue on Windows with Strawberry Perl 5.24.1

**Comment by tobyink** [comment]
Duplicate of https://rt.cpan.org/Ticket/Display.html?id=109841

It's caused by a bug in Devel::CallParser on threaded Perl 5.22+.

There's a patch to fix Devel::CallParser here:

https://rt.cpan.org/Ticket/Display.html?id=110623

However, its maintainer seems to be inactive lately. It may be that Devel::CallParser needs forking or something.

**Comment by cxw42** [comment]
For those running across this issue, TOBYINK [released](https://rt.cpan.org/Public/Bug/Display.html?id=110623#txn-1792767) a working version:

    cpanm Alt::Devel::CallParser::ButWorking

**Comment by bill-coacho** [comment]
cxw4w THANK YOU. Installed the ...ButWorking module. Net::Stripe now installs under Ubuntu 18.04, Perl 5.26.
bill

**Comment by bill-coacho** [comment]
Thank you.
The 2020 solution, installing  Alt::Devel::CallParser::ButWorking, worked again.
