### ISSUE TITLE
Possible to have method declaration order not matter?

### ISSUE THREAD

**Issue by srchulo** [tobyink/p5-kavorka#24]
It appears that method declaration order matters when using Kavorka, and I haven't been able to find any mention of this in the documentation.

This can be particularly problematic when creating a package that where methods use each other, because then you need to make sure the methods appear in dependent order. It also forces any lexical methods to go at the top of the package instead of the bottom.

Is it possible for order not to matter?

**Comment by tobyink** [comment]
With regards to lexical subs, with Perl's built in lexical sub stuff (`my sub foo { ... }`) you need to declare the sub before it gets used. Same as how lexical variables (`my $foo`) need to be declared before they are used.

For *methods*, it should absolutely not matter what order they're declared in. If you're finding that it does, I'd like to see a test case.

For functions, it may matter, depending on how you're calling the function and whether you're doing unusual stuff with prototypes. If you call the function using parentheses, it shouldn't matter.

```
use Kavorka;

fun foo (Int $x) {
	bar($x+1);  # bar not declared yet
}

fun bar (Any $y) {
	print "$y\n";
}

foo(41);
```

**Comment by srchulo** [comment]
Ah, I see. Well I saw this specifically with lexical subs. Does Kavorka work that way to be consistent with perl's built in lexical subs, or is that required based on how they are implemented?

**Comment by srchulo** [comment]
Okay, so there's no way around it. I guess the correct thing to do is just put lexical subs first?

Thanks for explaining! I'll close this issue.
