### ISSUE TITLE
Question about utility of 'method'

### ISSUE THREAD

**Issue by srchulo** [tobyink/p5-kavorka#26]
This is a request for maybe some more documentation around `method` vs `objectmethod`. I see the merit for `objectmethod` and `classmethod`, but I do not see the point of `method`. I can't imagine a situation where you would want a method that works on an object or a class-- it seems like for most methods of the form:

```
sub my_method {
    my $self = shift;

    # do object stuff
}
```

This would just break it if it was a class. I find myself wanting to type `method`, but I feel the need to always type the longer `objectmethod`, since that's what I really want :) Explanation in the docs as to how `method` is useful could help? My guess is most people use `method` since it's shorter, when what they really want is `objectmethod`.

**Comment by tobyink** [comment]
There certainly are cases where it makes sense to have a method that works as either:

```perl
say $bob->species;   # says "Homo sapiens"
say Human->species;  # says "Homo sapiens"
```

A `method` keyword is provided by Perl 6, which is the main source of inspiration for Kavorka's syntax, and it can be used for object or class methods.

I would generally suggest using `method` for most methods, and `classmethod` if you specifically want a class-only method. (There's usually no harm in allowing class methods to be called on objects, so `method` will often be fine for class methods too!) `method` will be faster than `objectmethod` or `classmethod` as it doesn't perform any type checking on the invocant.

**Comment by srchulo** [comment]
Okay, that makes sense. And I guess for using `method` for methods that only work on objects, you still get an error message at roughly the same time objectmethod would give it to you:

```
class Person :ro {
    has name => (isa => 'Str');

    method say_name { say $self->name }
}

Person->say_name;
```

`Can't use string ("Person") as a HASH ref while "strict refs" in use at (eval 247) line 18.`

Thanks for the clarifications! I don't know if you think any of this would be useful in the documentation, but I will close this for now.

**Comment by srchulo** [comment]
Although one thing that is interesting to note, is that the error message wouldn't tell the user of Moops where their error is occurring in their code.
